name: Deploy Backend to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /var/www/keibeauty-backend/KeiBeauty
            git pull origin main
            source /var/www/keibeauty-backend/venv/bin/activate
            pip install -r requirements.txt
            sudo systemctl restart keibeauty
            sudo systemctl restart nginx